### ISSUE TITLE
Adding an apt repository required by a dependency 

### ISSUE THREAD

**Issue by scottrobertson** [crohr/pkgr#123]
I have the following in my `.pkgr.yml` config file:

```
dependencies:
  - docker-ce
  - nginx
```

As you can see, I need to be able to install `docker-ce`. The issue is, that dependency requires the Docker repo to be added. What would be the best way to do this? 

https://docs.docker.com/engine/installation/linux/ubuntu/

I tried:

- Installing in the before_install hook, but dpkg is locked at that point
- Adding the dependency repo in before_install, but that is called after the dependency install is attempted

Any help would be appreciated.

**Comment by crohr** [comment]
Hello,

As far as I know there is no way to do this, because as you say you will encounter a locking issue when running the apt-get update. You could have a one-liner that sets the apt repository for both docker and your app, but you'll still need your user to fetch the relevant signing keys separately anyway.

**Comment by scottrobertson** [comment]
Hey @crohr, thanks for the reply.

Yeah that is basically what I have at the moment. I just have the users adding the signing key, and then I let pkgr manage the dependancies.
