### ISSUE TITLE
When ruby 2.4.1 is used the ruby 2.3.0 files are installed to vendor directory anyway

### ISSUE THREAD

**Issue by monotek** [crohr/pkgr#132]
Our Ruby app is using ruby 2.4.1.

This is resulting in DEB / RPM packages which are much bigger than normal, as the ruby 2.3.0 directory is also packaged inside the vendor directory.

Workaround is to remove the directory in the after step with:

* rm -r vendor/bundle/ruby/2.3.0

**Comment by monotek** [comment]
Seems to be fixed now.

**Comment by monotek** [comment]
Problem seems to be back for Zammad repo.

Have to remove the dir in build process again:
https://github.com/zammad/zammad/commit/a0e0dfcc3a083e4712db6e6214297b3816de9c1e

**Comment by crohr** [comment]
This issue seems to appear from time to time when people switch their language version. I'm not sure what's going on at the moment since the cache clearing mechanism happens in the buildpack, so would recommend force-clearing the cache directory on Packager.io the first time you switch to a new version of ruby.

**Comment by monotek** [comment]
Thanks for the hint. We'll try it...
