### ISSUE TITLE
Packaging Rails application with custom ruby patch

### ISSUE THREAD

**Issue by openface** [crohr/pkgr#160]
First, thanks for this excellent packaging tool!

We use pkgr for packaging a Rails (Gemfile specifies ruby 2.3.1) app.   We now have the need to apply a patch file to ruby itself.  Given that pkgr uses buildpacks, I assume we have to somehow modify the buildpack to include this patch, but I am not aware of where to start down that path.  I figured here would be a good place to ask.  Thanks.

**Comment by crohr** [comment]
Hello,

You would need to hack the buildpack to provide your own precompiled ruby version including the patch. By default `pkgr` will use the buildpack located at https://github.com/pkgr/heroku-buildpack-ruby/tree/v199-1, but you can override it with the `builldpack` option in your `.pkgr.yml` file, so that it points to a buildpack that you maintain yourself. It is quite some work though, maintenance-wise.
