### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by benlangfeld** [crohr/pkgr#51]
Is JRuby support on the horizon for Packager.io? Is there anything necessary to get official support into pkgr, which I guess would be the first step? I need this urgently on a project and am trying to evaluate our options.

**Comment by lukaszkorecki** [comment]
@benlangfeld for JRuby you probably want to check out https://github.com/jruby/warbler

**Comment by benlangfeld** [comment]
Actually, I quite liked the idea of sticking with pkgr's model (OS package manager, including ENV setup, init/upstart, etc), rather than something that simply spits out a .war; this would be a half-way step to what pkgr is. Is there something I'm missing?

**Comment by crohr** [comment]
@benlangfeld I can have a try this week to see what's missing for JRuby apps to work with pkgr (and thus packager.io). Just to reduce the scope at first, what would be your target distribution(s)?

**Comment by lukaszkorecki** [comment]
Just wanted to add my 2c:
- once you have a fully contained jar file you can easily turn it into a exectable file (which will only  depend on JVM)
- making that into a deb package is trivial with FPM

That said - there is https://github.com/jruby/heroku-buildpack-jruby which might just do the trick in pkgr cc @crohr

**Comment by benlangfeld** [comment]
@crohr Awesome! Against my preferences, we're initially targeting CentOS 6.

**Comment by crohr** [comment]
@benlangfeld it looks like it will work if you use the standard heroku ruby buildpack instead of the one we're using on [packager.io](https://packager.io) (jruby binaries are not available on our side yet, but it would be simple to fix). See https://packager.io/gh/crohr/heroku-jruby-example/install?bid=2 for instance, with the relevant changes at https://github.com/crohr/heroku-jruby-example/commit/cc2fd6123f112af078065f46c0d4cdb940ce6051.

After you install on CentOS you'll have:

```bash
$ sudo heroku-jruby-example run ruby -v
Picked up JAVA_TOOL_OPTIONS: -Xmx384m -Djava.rmi.server.useCodebaseOnly=true
jruby 1.7.11 (2.0.0p195) 2014-02-25 fffffff on OpenJDK 64-Bit Server VM 1.7.0_55-b14 [linux-amd64]
```

And you can `heroku-jruby-example scale web=1` and it will work.

Let me know if it works for your app, and in that case I'll make the necessary changes so that it works out of the box on [packager.io](https://packager.io) (and with `pkgr`).

**Comment by benlangfeld** [comment]
Awesome, thanks for the fast response @crohr. I'll check it out with a manual build ASAP and give you my feedback.

**Comment by crohr** [comment]
@benlangfeld if you're using `pkgr` locally, don't forget to run with `pkgr package --env STACK=cedar CURL_CONNECT_TIMEOUT=30 CURL_TIMEOUT=600 ...` because the default `curl` timeouts of the heroku buildpack are very aggressive.

Let me know how it goes.

**Comment by benlangfeld** [comment]
Seems to work great, @crohr!

**Comment by crohr** [comment]
Great, I'll add official support on packager.io very soon, though you can already use it there if needed with the `buildpack` option ;)
